npm: npm package publish and installable
Major-Project-BE2018SE/polaris-suite pull request #8
Opened 2023-04-13 03:05 UTC by alsongarbuja

This pull request contains code updates for the project to be published in the npm package website and able to install in other projects using `npm i polaris-suite`

Still need to do
- [ ] able to use custom command such as `polaris` to perform unit testing
- [ ] able to compile from `ts` to `js`

2023-04-16 16:29 UTC, Salipa-Gurung requested changes

2023-04-16 16:29 UTC, Salipa-Gurung commented on bin/test.ts
should be able to run with folder name containing space ` New folder`

2023-04-16 16:29 UTC, Salipa-Gurung commented on bin/test.ts
fix text coloring format for test results

2023-04-17 05:49 UTC, alsongarbuja commented on bin/test.ts
This one is fixed by using the `spwan` function of `child_process` from node js instead of `shelljs` package.

2023-04-25 07:11 UTC, Prasiddha777 approved these changes

2023-04-30 13:48 UTC, Salipa-Gurung approved these changes

2023-04-30 13:48 UTC, merged